spring:
  data:
    mongodb:
      authentication-database:
      port: 27017
      host: 127.0.0.1
      database: otus_hw_08

mongock:
  runner-type: "ApplicationRunner"
  change-logs-scan-package:
    - ru.otus.hw.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
